### ISSUE TITLE
 featured Post and delete post  functions are not  working

### ISSUE THREAD

**Issue by Indula-Perera** [profabhishekjha/MacBlog#1]
I will wait until you complete this

**Comment by profabhishekjha** [comment]
Actually featured post is working, I have sorted that aaray according to
views

**Comment by Indula-Perera** [comment]
did you commit that part

**Comment by profabhishekjha** [comment]
Yeah you can check that in the code itself, api name is featuredpost or
something for the front page post, and to delete the post , I will complete
that soon, if you have any problem, please let me know
